# Generated by Django 3.0 on 2020-06-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cart1',
        ),
    ]
