# Generated by Django 3.0 on 2020-06-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200620_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='user_price',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
