# Generated by Django 3.0 on 2020-06-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_cart1_user_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='user_date',
            field=models.CharField(default=6, max_length=60),
            preserve_default=False,
        ),
    ]
