# Generated by Django 3.0 on 2020-06-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_cart1_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='user_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
