# Generated by Django 3.0 on 2020-06-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_cart1_user_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart1',
            name='user_date',
        ),
    ]
