# Generated by Django 3.0 on 2020-06-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_cart1_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='user_file',
            field=models.FileField(default=5, upload_to=''),
            preserve_default=False,
        ),
    ]
