# Generated by Django 3.0 on 2020-06-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_cart1_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='user_file',
            field=models.FileField(upload_to='hinhanh'),
        ),
    ]
